[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:bootstrap]
command=/etc/firstrun/firstrun.sh
extra_heavy_lifting_required=true
autorestart=false
startsecs=0

[program:guacd]
command=/opt/guacamole/sbin/guacd -b 0.0.0.0 -L %(ENV_GUACD_LOG_LEVEL)s -f
user=abc
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:mariadb]
command=/etc/firstrun/mariadb.sh
user=abc
stdout_logfile=/config/log/mariadb.log
stderr_logfile=/config/log/mariadb.log
autorestart=true

[program:tomcat]
command=/etc/firstrun/tomcat-wrapper.sh
user=abc
stdout_logfile=/config/log/tomcat.log
stderr_logfile=/config/log/tomcat.log
autorestart=true
