[supervisord]
nodaemon=true
user=root
logfile=/config/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:bootstrap]
command=/etc/firstrun/firstrun.sh
priority=1
autorestart=false
startsecs=0
stdout_logfile=/config/log/bootstrap.log
stderr_logfile=/config/log/bootstrap.log

[program:mariadb]
command=/etc/firstrun/mariadb.sh
priority=10
user=abc
autorestart=true
stdout_logfile=/config/log/mariadb.log
stderr_logfile=/config/log/mariadb.log

[program:guacd]
command=/opt/guacamole/sbin/guacd -b 0.0.0.0 -f
priority=20
user=abc
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:tomcat]
command=/etc/firstrun/tomcat-wrapper.sh
priority=30
user=abc
stdout_logfile=/config/log/tomcat.log
stderr_logfile=/config/log/tomcat.log
